**Youtube-Influencer-Analysis-case-study**-

1) Reading the above CSV file in google colab using the pandasâ€™ library and converting it into data frames.

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df1=pd.read_csv("/content/Youtube Influencer Analysis - Updated.csv",encoding='mac_roman')
df1

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,00:14:24,864.00,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,Female,458,72945,0:08:12,492.00,...,Yes,0,0,NaN,720,158,0.0,No,0,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,NaN,1680000,541653219,0:01:06,66.00,...,Yes,0,77,9/22/2022,1080,46509,48.0,No,20,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,NaN,12100000,3600496171,0:07:40,460.00,...,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1,Rahul Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,https://www.youtube.com/watch?v=GS18WawA-t0,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,https://www.youtube.com/c/SahilOnlineTVnews,Sahil Online TV News,NaN,594000,129926690,00:13:47,827.00,...,Yes,0,15,10/4/2022,1080,5024,36.0,No,1,Mafaz Ali
901,https://www.youtube.com/watch?v=_tc_APkjH2Q,"16,554",Amchi Nawayat Mehfil hee,https://www.youtube.com/sahilonline,Sahil Online TV News,NaN,594000,129926690,00:06:44,404.00,...,Yes,2,0,10/4/2022,720,5024,36.0,No,1,Mafaz Ali
902,https://www.youtube.com/watch?v=Xfj4osSYfhU,"32,798",Aas ge Kaagaz,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,NaN,23500,5104872,00:06:24,384.00,...,Yes,3,0,8/4/2022,720,1018,13.0,No,1,Mafaz Ali
903,https://www.youtube.com/watch?v=mGEHqwVz0eI,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,NaN,23500,5104872,00:04:39,279.00,...,Yes,3,0,8/4/2022,1080,1018,13.0,No,1,Mafaz Ali
904,https://www.youtube.com/watch?v=UGATpt0I4vA,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,https://www.youtube.com/c/SonySportsNetwork,Sony Sports Network,NaN,3980000,728858923,00:01:21,81.00,...,Yes,3,0,10/4/2022,1080,3014,124.0,No,0,Mafaz Ali

In [ ]:
df1.head()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,00:14:24,864.00,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,Female,458,72945,0:08:12,492.00,...,Yes,0,0,NaN,720,158,0.0,No,0,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,NaN,1680000,541653219,0:01:06,66.00,...,Yes,0,77,9/22/2022,1080,46509,48.0,No,20,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,NaN,12100000,3600496171,0:07:40,460.00,...,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1,Rahul Singh

2) How many values are missing for each column and try dropping or replacing NULL values using appropriate pandasâ€™ function.

In [ ]:
#Number of missing values
df2=df1.isnull().sum()
df2

Video Link                                 0
Video Views                                0
Video Title                                0
Channel URL                                0
Creator Name                              11
Creator Gender                           314
Total Channel Subcribers                   0
Total Chanel Views                         0
Duration of Video                          0
Duration in Seconds                        0
Date of Video Upload                       0
No of Likes                                1
Language of the Video                     21
Subtitle                                   1
Video Description                          0
Hashtags                                   0
No of Comments                             0
Date of the Last Comment                  24
Maximum Quality of the Video               0
No of Videos the Channel                   0
No of Playlist                             9
Premiered or Not                           0
Community Engagement (Posts per week)      0
Intern Who Collected the Data              0
dtype: int64

In [ ]:
#Replacing Null values with an "unknown"
df1.fillna("unknown")

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,00:14:24,864.00,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,Female,458,72945,0:08:12,492.00,...,Yes,0,0,unknown,720,158,0.0,No,0,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,unknown,1680000,541653219,0:01:06,66.00,...,Yes,0,77,9/22/2022,1080,46509,48.0,No,20,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,unknown,12100000,3600496171,0:07:40,460.00,...,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1,Rahul Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,https://www.youtube.com/watch?v=GS18WawA-t0,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,https://www.youtube.com/c/SahilOnlineTVnews,Sahil Online TV News,unknown,594000,129926690,00:13:47,827.00,...,Yes,0,15,10/4/2022,1080,5024,36.0,No,1,Mafaz Ali
901,https://www.youtube.com/watch?v=_tc_APkjH2Q,"16,554",Amchi Nawayat Mehfil hee,https://www.youtube.com/sahilonline,Sahil Online TV News,unknown,594000,129926690,00:06:44,404.00,...,Yes,2,0,10/4/2022,720,5024,36.0,No,1,Mafaz Ali
902,https://www.youtube.com/watch?v=Xfj4osSYfhU,"32,798",Aas ge Kaagaz,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,unknown,23500,5104872,00:06:24,384.00,...,Yes,3,0,8/4/2022,720,1018,13.0,No,1,Mafaz Ali
903,https://www.youtube.com/watch?v=mGEHqwVz0eI,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,unknown,23500,5104872,00:04:39,279.00,...,Yes,3,0,8/4/2022,1080,1018,13.0,No,1,Mafaz Ali
904,https://www.youtube.com/watch?v=UGATpt0I4vA,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,https://www.youtube.com/c/SonySportsNetwork,Sony Sports Network,unknown,3980000,728858923,00:01:21,81.00,...,Yes,3,0,10/4/2022,1080,3014,124.0,No,0,Mafaz Ali

3) Drop the columns which are irrelevant features to feed into our model.

In [ ]:
df2=df1.drop(columns=['Video Link','Channel URL','Intern Who Collected the Data'])
df2

,Video Views,Video Title,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,Date of Video Upload,No of Likes,...,Subtitle,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week)
0,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",7/29/2022,6700.0,...,No,Yes,0,419,8/6/2022,1080,462,12.0,No,1
1,"231,969",Bhoom Baddhal Web Series,Chai Bisket,Male,920000,137535681,00:14:24,864.00,5/22/2022,7800.0,...,No,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2
2,878,"Customer Psychology, Four Views Of Consumer De...",Virda Warsi,Female,458,72945,0:08:12,492.00,2/9/2021,858.0,...,No,Yes,0,0,NaN,720,158,0.0,No,0
3,"9,965",Top countries with proven natural gas reserves,TRT,NaN,1680000,541653219,0:01:06,66.00,9/13/2022,188.0,...,No,Yes,0,77,9/22/2022,1080,46509,48.0,No,20
4,"39,780,561",73 Questions With Selena Gomez,Vogue,NaN,12100000,3600496171,0:07:40,460.00,3/21/2017,901000.0,...,yes,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,Sahil Online TV News,NaN,594000,129926690,00:13:47,827.00,9/29/2022,235.0,...,No,Yes,0,15,10/4/2022,1080,5024,36.0,No,1
901,"16,554",Amchi Nawayat Mehfil hee,Sahil Online TV News,NaN,594000,129926690,00:06:44,404.00,8/6/2017,117.0,...,No,Yes,2,0,10/4/2022,720,5024,36.0,No,1
902,"32,798",Aas ge Kaagaz,Sahil Online Bhatkal,NaN,23500,5104872,00:06:24,384.00,1/3/2021,1.0,...,No,Yes,3,0,8/4/2022,720,1018,13.0,No,1
903,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,Sahil Online Bhatkal,NaN,23500,5104872,00:04:39,279.00,3/6/2022,1.0,...,No,Yes,3,0,8/4/2022,1080,1018,13.0,No,1
904,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,Sony Sports Network,NaN,3980000,728858923,00:01:21,81.00,9/25/2022,7600.0,...,Yes,Yes,3,0,10/4/2022,1080,3014,124.0,No,0

4) Some columns are not statistical data but in the form of strings. It Is difficult for our model to learn when the data is in form of strings. Your task is to encode these strings using proper encoding techniques.

In [ ]:
df2.dtypes

#OBJECT - MIXED NUMBER AND STRING 
#FLOAT564 - WITH DECIMAL
#INT64 - 	NUMERIC CHARACTER

Video Views                               object
Video Title                               object
Creator Name                              object
Creator Gender                            object
Total Channel Subcribers                  object
Total Chanel Views                        object
Duration of Video                         object
Duration in Seconds                       object
Date of Video Upload                      object
No of Likes                              float64
Language of the Video                     object
Subtitle                                  object
Video Description                         object
Hashtags                                   int64
No of Comments                            object
Date of the Last Comment                  object
Maximum Quality of the Video               int64
No of Videos the Channel                   int64
No of Playlist                           float64
Premiered or Not                          object
Community Engagement (Posts per week)      int64
dtype: object

In [ ]:
stt=['Creator Gender','Subtitle','Video Description','Premiered or Not']

In [ ]:
#Encoding 
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df2[stt]= df2[stt].apply(labelencoder.fit_transform)
df2

,Video Views,Video Title,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,Date of Video Upload,No of Likes,...,Subtitle,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week)
0,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,srihari ck,2,40200,7964284,00:30:41,"1,841.00",7/29/2022,6700.0,...,0,2,0,419,8/6/2022,1080,462,12.0,0,1
1,"231,969",Bhoom Baddhal Web Series,Chai Bisket,2,920000,137535681,00:14:24,864.00,5/22/2022,7800.0,...,0,2,1,189,6/15/2022,1080,251,12.0,1,2
2,878,"Customer Psychology, Four Views Of Consumer De...",Virda Warsi,1,458,72945,0:08:12,492.00,2/9/2021,858.0,...,0,2,0,0,NaN,720,158,0.0,0,0
3,"9,965",Top countries with proven natural gas reserves,TRT,3,1680000,541653219,0:01:06,66.00,9/13/2022,188.0,...,0,2,0,77,9/22/2022,1080,46509,48.0,0,20
4,"39,780,561",73 Questions With Selena Gomez,Vogue,3,12100000,3600496171,0:07:40,460.00,3/21/2017,901000.0,...,2,2,0,28221,9/23/2022,1080,2872,113.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,Sahil Online TV News,3,594000,129926690,00:13:47,827.00,9/29/2022,235.0,...,0,2,0,15,10/4/2022,1080,5024,36.0,0,1
901,"16,554",Amchi Nawayat Mehfil hee,Sahil Online TV News,3,594000,129926690,00:06:44,404.00,8/6/2017,117.0,...,0,2,2,0,10/4/2022,720,5024,36.0,0,1
902,"32,798",Aas ge Kaagaz,Sahil Online Bhatkal,3,23500,5104872,00:06:24,384.00,1/3/2021,1.0,...,0,2,3,0,8/4/2022,720,1018,13.0,0,1
903,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,Sahil Online Bhatkal,3,23500,5104872,00:04:39,279.00,3/6/2022,1.0,...,0,2,3,0,8/4/2022,1080,1018,13.0,0,1
904,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,Sony Sports Network,3,3980000,728858923,00:01:21,81.00,9/25/2022,7600.0,...,1,2,3,0,10/4/2022,1080,3014,124.0,0,0

In [ ]:
df2.dtypes

Video Views                               object
Video Title                               object
Creator Name                              object
Creator Gender                             int64
Total Channel Subcribers                  object
Total Chanel Views                        object
Duration of Video                         object
Duration in Seconds                       object
Date of Video Upload                      object
No of Likes                              float64
Language of the Video                     object
Subtitle                                   int64
Video Description                          int64
Hashtags                                   int64
No of Comments                            object
Date of the Last Comment                  object
Maximum Quality of the Video               int64
No of Videos the Channel                   int64
No of Playlist                           float64
Premiered or Not                           int64
Community Engagement (Posts per week)      int64
dtype: object